### ISSUE TITLE
A couple suggestions.

### ISSUE THREAD

**Issue by JonCris** [Darkorg69/BetterPunching#2]
**Describe your suggestion**

Is there a way to include a normal config on the config folder? Or is there a way to include the configs into a modpack?

- Make duration of effects configurable and or being able to configure the effect given. 
- Config to add custom blocks and the tool used to break them.

**Comment by Darkorg69** [comment]
Thank you for your suggestions.
I will add more configurations with next update.
I'm unsure if the second suggestion can be implemented, but I will look into it.

**Comment by zargogo** [comment]
Please also update it for 1.16.5 :-)

**Comment by Darkorg69** [comment]
About the configs into a modpack, just copy over the config file into defaultconfigs folder, from then every new world you create will use the same settings!
